# Generated by Django 3.2 on 2021-07-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpBo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bo', models.CharField(default='', help_text='BO Names', max_length=50)),
            ],
            options={
                'db_table': 'imp_bo',
            },
        ),
    ]
