# Generated by Django 3.2 on 2021-07-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_bo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impbo',
            name='bo',
            field=models.CharField(default='', help_text='BO Names', max_length=10),
        ),
    ]
