# Generated by Django 3.2 on 2021-07-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_bo', '0002_alter_impbo_bo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impbo',
            name='bo',
            field=models.CharField(default='', help_text='BO Names', max_length=20),
        ),
    ]
