# Generated by Django 3.2 on 2021-07-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_bu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impbu',
            old_name='bgid',
            new_name='bg',
        ),
        migrations.RenameField(
            model_name='impbu',
            old_name='boid',
            new_name='bo',
        ),
        migrations.AlterField(
            model_name='impbu',
            name='bu',
            field=models.CharField(default='', help_text='BU Names', max_length=20),
        ),
    ]
