# Generated by Django 3.2.6 on 2021-10-15 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_bu', '0002_auto_20210721_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impbu',
            options={'ordering': ['bu', 'bg', 'bo']},
        ),
    ]
