# Generated by Django 3.2.12 on 2022-03-23 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pms_project', '0007_auto_20220224_1025'),
        ('pms_jira_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmsProjectUserLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_user_id', models.IntegerField(default=0, help_text='Project User ID')),
                ('user_id', models.IntegerField(default=0, help_text='User ID')),
                ('project_id', models.IntegerField(default=0, help_text='Project ID')),
                ('project_role', models.CharField(help_text='Project Role', max_length=20)),
                ('jira_role', models.CharField(help_text='Jira Role', max_length=15)),
                ('join_date', models.DateTimeField(auto_now_add=True, help_text='Join Date')),
                ('action', models.CharField(help_text='Action', max_length=10)),
                ('trn_date', models.DateTimeField(auto_now_add=True, help_text='Tansaction Date')),
                ('trn_user', models.CharField(help_text='Tansaction User', max_length=50)),
            ],
            options={
                'db_table': 'pms_prj_user_log',
                'ordering': ['project_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PmsProjectUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_role', models.CharField(help_text='Project Role', max_length=20)),
                ('jira_role', models.CharField(help_text='Jira Role', max_length=15)),
                ('join_date', models.DateTimeField(auto_now_add=True, help_text='Join Date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pms_prj_user_project_id_fkey', to='pms_project.pmsproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pms_prj_user_user_id_fkey', to='pms_jira_user.pmsjirauser')),
            ],
            options={
                'db_table': 'pms_prj_user',
                'ordering': ['project_id', 'id'],
                'unique_together': {('project_id', 'user_id')},
            },
        ),
    ]
