# Generated by Django 3.2.12 on 2022-03-29 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms_project', '0007_auto_20220224_1025'),
        ('pms_jira_user', '0006_delete_pmsjirausergroup'),
        ('pms_project_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmsprojectuser',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pms_prj_user_project_id_fkey', to='pms_project.pmsproject'),
        ),
        migrations.AlterField(
            model_name='pmsprojectuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pms_prj_user_user_id_fkey', to='pms_jira_user.pmsjirauser'),
        ),
    ]
