# Generated by Django 3.2.12 on 2022-04-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_project_user', '0002_auto_20220329_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmsprojectuser',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Wait for Delete from Project'),
        ),
    ]
