# Generated by Django 3.2.12 on 2022-05-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_project_user', '0003_pmsprojectuser_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmsprojectuserlog',
            name='approved',
            field=models.BooleanField(default=False, help_text='Approved'),
        ),
    ]
