# Generated by Django 3.2.12 on 2022-05-05 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms_sign', '0002_rename_remark_pmssign_requester_remark'),
        ('pms_project_user', '0005_auto_20220505_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmsprojectuserlog',
            name='sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pms_prj_user_log_sign_id_fkey', to='pms_sign.pmssign'),
        ),
    ]
