# Generated by Django 3.2.12 on 2022-05-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms_jira_user', '0006_delete_pmsjirausergroup'),
        ('pms_project', '0009_pmsproject_jira_project_id'),
        ('pms_project_user', '0006_pmsprojectuserlog_sign'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pmsprojectuser',
            unique_together={('project_id', 'user_id', 'deleted')},
        ),
    ]
