# Generated by Django 3.2.12 on 2022-04-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PmsJiraITUser',
            fields=[
                ('jira_user_id', models.CharField(help_text='Jira User ID', max_length=100, primary_key=True, serialize=False)),
                ('display_name', models.CharField(help_text='Jira User Name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'pms_jira_it_user',
                'ordering': ['jira_user_id'],
            },
        ),
    ]
