# Generated by Django 3.2 on 2021-07-14 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imp_div', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpTssPast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pmcsibprojectyear', models.CharField(default='', help_text='IB Project Year', max_length=4)),
                ('pmcsibprojectname', models.CharField(default='', help_text='IB Project Name', max_length=100)),
                ('ibcode', models.CharField(default='', help_text='IB Code', max_length=12)),
                ('itpm', models.CharField(default='', help_text='Project IT PMe', max_length=50)),
                ('workmonth', models.CharField(default='', help_text='Work Month on TSS', max_length=10)),
                ('workhours', models.FloatField(help_text='Work Hour on TSS')),
                ('days', models.IntegerField(help_text='Work Days', max_length=3)),
                ('tssmm', models.FloatField(help_text=' Man-Month on TSS')),
                ('divid', models.ForeignKey(help_text='Division ID', on_delete=django.db.models.deletion.CASCADE, to='imp_div.impdiv')),
            ],
            options={
                'db_table': 'imp_tsspast',
                'unique_together': {('id', 'ibcode')},
            },
        ),
    ]
