# Generated by Django 3.2 on 2021-07-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_tsspast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imptsspast',
            name='days',
            field=models.IntegerField(help_text='Work Days'),
        ),
    ]
