# Generated by Django 3.2 on 2021-07-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_tsspast', '0002_alter_imptsspast_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imptsspast',
            old_name='divid',
            new_name='div',
        ),
    ]
