# Generated by Django 3.2 on 2021-07-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_tsspast', '0003_rename_divid_imptsspast_div'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imptsspast',
            old_name='ibcode',
            new_name='ib_code',
        ),
        migrations.RenameField(
            model_name='imptsspast',
            old_name='itpm',
            new_name='it_pm',
        ),
        migrations.RenameField(
            model_name='imptsspast',
            old_name='pmcsibprojectname',
            new_name='pmcs_ib_project_name',
        ),
        migrations.RenameField(
            model_name='imptsspast',
            old_name='pmcsibprojectyear',
            new_name='pmcs_ib_project_year',
        ),
        migrations.RenameField(
            model_name='imptsspast',
            old_name='tssmm',
            new_name='tss_mm',
        ),
        migrations.RenameField(
            model_name='imptsspast',
            old_name='workhours',
            new_name='work_hours',
        ),
        migrations.RenameField(
            model_name='imptsspast',
            old_name='workmonth',
            new_name='work_month',
        ),
        migrations.AlterUniqueTogether(
            name='imptsspast',
            unique_together={('id', 'ib_code')},
        ),
    ]
