# Generated by Django 3.2.12 on 2022-03-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_tsspast', '0005_rename_div_imptsspast_div_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imptsspast',
            name='div_group',
            field=models.CharField(default='', help_text='Division Group', max_length=30),
        ),
    ]
