# Generated by Django 3.2.12 on 2022-03-10 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_tsspast', '0006_alter_imptsspast_div_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imptsspast',
            unique_together={('id', 'pmcs_ib_project_year', 'pmcs_ib_project_name', 'ib_code', 'div_group')},
        ),
    ]
