# Generated by Django 3.2.12 on 2022-03-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_jira_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmsjirauser',
            name='jiraGroup',
            field=models.TextField(help_text='Jira Group', null=True),
        ),
    ]
