# Generated by Django 3.2.12 on 2022-03-25 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms_jira_user', '0002_pmsjirauser_jiragroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pmsjirauser',
            old_name='jiraGroup',
            new_name='jira_group',
        ),
    ]
