# Generated by Django 3.2.12 on 2022-03-29 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms_jira_user', '0004_remove_pmsjirauser_jira_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmsJiraUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pms_jira_user.pmsjirauser')),
            ],
        ),
    ]
