# Generated by Django 3.2.12 on 2022-03-28 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pms_jira_user', '0004_remove_pmsjirauser_jira_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmsJiraUserGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jira_group', models.CharField(help_text='Jira Group', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pms_jira_user_group_user_id_fkey', to='pms_jira_user.pmsjirauser')),
            ],
            options={
                'db_table': 'pms_jira_user_group',
                'ordering': ['user_id', 'id'],
            },
        ),
    ]
