# Generated by Django 3.2.12 on 2022-03-29 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms_jira_user', '0006_delete_pmsjirausergroup'),
        ('pms_jira_user_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmsjirausergroup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pms_jira_user_group_user_id_fkey', to='pms_jira_user.pmsjirauser'),
        ),
    ]
