# Generated by Django 3.1.7 on 2022-01-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmsProjectLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.IntegerField(default=0, help_text='Status')),
                ('project_name', models.CharField(help_text='Project Name', max_length=50)),
                ('division', models.CharField(help_text='Division', max_length=10)),
                ('division_supervisor', models.CharField(help_text='Division Supervison', max_length=50)),
                ('division_supervisor_email', models.TextField(help_text='Division Supervison EMail')),
                ('mode', models.CharField(help_text='Mode', max_length=10)),
                ('product_type', models.TextField(help_text='Product Type')),
                ('plan_start', models.DateField(help_text='Plan Start')),
                ('plan_end', models.DateField(help_text='Plan End')),
                ('jira_key', models.CharField(help_text='Jira Key', max_length=10)),
                ('jira_name', models.CharField(help_text='Jira Name', max_length=100)),
                ('user_contact', models.CharField(help_text='User Contact', max_length=50)),
                ('user_contact_email', models.TextField(help_text='User Contact EMail')),
                ('it_contact', models.CharField(help_text='IT Contact', max_length=50)),
                ('it_contact_email', models.TextField(help_text='IT Contact EMail')),
                ('status', models.IntegerField(default=0, help_text='Status')),
                ('involve_pms', models.BooleanField(default=True, help_text='Involve PMS')),
                ('involve_pms_start', models.DateField(help_text='Involve PMS Start Date', null=True)),
                ('involve_pms_end', models.DateField(help_text='Involve PMS End Date', null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='Create Date')),
                ('close_date', models.DateTimeField(help_text='Close Date', null=True)),
                ('approve_date', models.DateTimeField(help_text='Approve Date', null=True)),
                ('action', models.CharField(help_text='Action', max_length=10)),
                ('trn_date', models.DateTimeField(auto_now_add=True, help_text='Tansaction Date')),
                ('trn_user', models.CharField(help_text='Tansaction User', max_length=50)),
            ],
            options={
                'db_table': 'pms_prj_list_log',
                'ordering': ['project_name'],
            },
        ),
    ]
