# Generated by Django 3.1.7 on 2022-01-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_project', '0002_pmsprojectlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmsprojectlog',
            name='create_date',
            field=models.DateTimeField(help_text='Create Date'),
        ),
    ]
