# Generated by Django 3.1.7 on 2022-02-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_project', '0003_auto_20220127_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmsprojectlog',
            name='project_id',
            field=models.IntegerField(default=0, help_text='Project ID'),
        ),
    ]
