# Generated by Django 3.1.7 on 2022-02-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_project', '0004_auto_20220207_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmsproject',
            name='close',
            field=models.BooleanField(default=False, help_text='Close'),
        ),
        migrations.AddField(
            model_name='pmsprojectlog',
            name='close',
            field=models.BooleanField(default=False, help_text='Close'),
        ),
    ]
