# Generated by Django 3.1.7 on 2022-02-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_project', '0005_auto_20220208_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmsproject',
            name='project_code',
            field=models.CharField(default='', help_text='Project Code', max_length=12),
        ),
        migrations.AddField(
            model_name='pmsprojectlog',
            name='project_code',
            field=models.CharField(default='', help_text='Project Code', max_length=12),
        ),
    ]
