# Generated by Django 3.1.7 on 2022-02-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_project', '0006_auto_20220217_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmsproject',
            name='create_user',
            field=models.CharField(default='', help_text='Create User', max_length=50),
        ),
        migrations.AddField(
            model_name='pmsprojectlog',
            name='create_user',
            field=models.CharField(default='', help_text='Create User', max_length=50),
        ),
    ]
