# Generated by Django 3.2.12 on 2022-04-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_project', '0008_auto_20220331_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmsproject',
            name='jira_project_id',
            field=models.IntegerField(help_text='Jira Project ID', null=True),
        ),
    ]
