# Generated by Django 3.2.12 on 2022-05-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_project', '0009_pmsproject_jira_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmsproject',
            name='confluence',
            field=models.BooleanField(default=False, help_text='Need To Create Confluence'),
        ),
        migrations.AddField(
            model_name='pmsproject',
            name='confluence_key',
            field=models.CharField(help_text='Confluence Key', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pmsproject',
            name='confluence_name',
            field=models.CharField(help_text='Confluence Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pmsprojectlog',
            name='confluence',
            field=models.BooleanField(default=False, help_text='Need To Create Confluence'),
        ),
        migrations.AddField(
            model_name='pmsprojectlog',
            name='confluence_key',
            field=models.CharField(help_text='Confluence Key', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pmsprojectlog',
            name='confluence_name',
            field=models.CharField(help_text='Confluence Name', max_length=100, null=True),
        ),
    ]
