# Generated by Django 3.2.9 on 2022-06-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_project', '0010_auto_20220531_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmsproject',
            name='mvp_date',
            field=models.DateField(help_text='MVP Date', null=True),
        ),
        migrations.AddField(
            model_name='pmsprojectlog',
            name='mvp_date',
            field=models.DateField(help_text='MVP Date', null=True),
        ),
    ]
