# Generated by Django 3.2.12 on 2022-04-06 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v_pms_register_jira_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vpmsregisterjirauser',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
