# Generated by Django 3.2 on 2021-07-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_extnames', '0002_rename_divid_extnames_div'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extnames',
            old_name='empname',
            new_name='emp_name',
        ),
    ]
