# Generated by Django 3.2.6 on 2021-09-27 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_extnames', '0003_rename_empname_extnames_emp_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extnames',
            old_name='div',
            new_name='div_group',
        ),
    ]
