# Generated by Django 3.2.6 on 2021-10-15 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_extnames', '0004_rename_div_extnames_div_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extnames',
            options={'ordering': ['emp_name', 'div_group']},
        ),
    ]
