"""
Django settings for DjangoAPI project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from pickle import TRUE

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-uzry8vv))*hd@wdf0w66mt8%6#v)5!p^9&0*22t_5%fwb&&5ga"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = [
#       "127.0.0.1:8000",
#       "127.0.0.1",
#       "10.37.65.1",
#       "imp-api.k8sqas-whq.k8s.wistron.com",
#       "imp-api.k8sprd-whq.k8s.wistron.com",
#       "localhost:8000",
#       "localhost"
# ]

ALLOWED_HOSTS = ["*",]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework.authtoken",
    "corsheaders",
    "rest_framework",
    "drf_yasg",
    "uploader",
    "imp_bo",
    "imp_bg",
    "imp_bu",
    "imp_div",
    "imp_dept",
    "imp_cal",
    "imp_projcategory",
    "imp_projtype",
    "imp_bud",
    "imp_budln",
    "imp_extnames",
    "imp_ib",
    "imp_ibln",
    "imp_pajln",
    "imp_pajmonth",
    "imp_pajtxt",
    "imp_prf",
    "imp_prfln",
    "imp_resource",
    "imp_tss",
    "imp_tsspast",
    "pms_project",
    "pms_project_log",
    "pms_jira_it_user",
    "pms_jira_user",
    "pms_jira_user_group",
    "pms_project_version_control",
    "pms_project_user",
    "pms_jira_project_role",
    "pms_common",
    "pms_sign",
    "v_pms_register_jira_user",
    "v_pms_delete_jira_user",
    "v_pms_user_in_jira"
]
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = "DjangoAPI.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "DjangoAPI.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
#     }
# }
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",  # PostgreSQL QAS
        "NAME": "impadmin",  # 資料庫名稱
        "USER": "impadmin",  # 資料庫帳號
        "PASSWORD": "Wistron2021",  # 資料庫密碼
        "HOST": "active.impqasqas.service.paas.wistron.com",
        "PORT": "15071"
        # "HOST": "active.impprdprd.service.paas.wistron.com",  # Server(伺服器)位址
        # "PORT": "15036" # PostgreSQL Port號
    }
}

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",  # PostgreSQL PRD
#         "NAME": "impadmin",  # 資料庫名稱
#         "USER": "impadmin",  # 資料庫帳號
#         "PASSWORD": "Wistron2021",  # 資料庫密碼
#         "HOST": "active.impprdprd.service.paas.wistron.com",  # Server(伺服器)位址
#         "PORT": "15036",  # PostgreSQL Port號
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTHENTICATION_BACKENDS = (("django.contrib.auth.backends.ModelBackend"),)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",  # <-- And here
    ],
    # "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",
    "TEST_REQUEST_DEFAULT_FORMAT": "json"
    # "PAGE_SIZE": 10,
}
SWAGGER_SETTINGS = {
    # 基础样式
    'SECURITY_DEFINITIONS': {

        "basic":{

            'type': 'basic'
        }
    },
    # 到处文件配置
    'DEFAULT_INFO': 'DjangoAPI.urls.schema_view',
    'USE_SESSION_AUTH': False,
     # 接口文档中方法列表以首字母升序排列
    'APIS_SORTER': 'alpha',
    # 如果支持json提交, 则接口文档中包含json输入框
    'JSON_EDITOR': True,
    # 方法列表字母排序
    'OPERATIONS_SORTER': 'alpha',
    'VALIDATOR_URL': None,
}

USE_X_FORWARDED_HOST = True
CORS_ORIGIN_ALLOW_ALL = True
CSRF_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "HTTPS")

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'localhost'  #SMTP伺服器
EMAIL_PORT = 25  #TLS通訊埠號
EMAIL_USE_TLS = False  #開啟TLS(傳輸層安全性)
EMAIL_HOST_USER = 'IMP@wistron.com'  #寄件者電子郵件
PMS_EMAIL_CC = ['Scott_Yang@wistron.com']
IMP_URL = 'https://imp-ui.k8sqas-whq.k8s.wistron.com/'

# Setting for MQTT Using
MQTTT_TOGGLE= True
MQTT_HOST="10.66.28.51"
MQTT_PORT=1883
MQTT_TOPICS= {
    "SUCCESS" : "wih/imp/{UserId}/message",
    "ERROR": "wih/imp/{UserId}/error"
}
# Setting for MQTT Using
