# Generated by Django 3.2 on 2021-07-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PajMonth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref', models.CharField(default='', help_text='Ref', max_length=1)),
                ('pajyear', models.CharField(default='', help_text='PAJ Year', max_length=4)),
                ('pajmonth', models.CharField(default='', help_text='PAJ Month', max_length=5)),
            ],
            options={
                'db_table': 'imp_pajmonth',
            },
        ),
    ]
