# Generated by Django 3.2 on 2021-07-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_pajmonth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pajmonth',
            old_name='pajmonth',
            new_name='paj_month',
        ),
        migrations.RenameField(
            model_name='pajmonth',
            old_name='pajyear',
            new_name='paj_year',
        ),
    ]
