# Generated by Django 3.2.12 on 2022-03-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_pajmonth', '0002_auto_20210721_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pajmonth',
            name='paj_month',
        ),
        migrations.RemoveField(
            model_name='pajmonth',
            name='paj_year',
        ),
        migrations.AddField(
            model_name='pajmonth',
            name='project_month',
            field=models.CharField(default='', help_text='Project Month', max_length=5),
        ),
        migrations.AddField(
            model_name='pajmonth',
            name='project_year',
            field=models.CharField(default='', help_text='Project Year', max_length=4),
        ),
    ]
