# Generated by Django 3.2.12 on 2022-03-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpPrf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_year', models.CharField(default='', help_text='Project Year', max_length=4)),
                ('project_name', models.CharField(default='', help_text='Project Name', max_length=100)),
                ('it_pm', models.CharField(blank=True, default='', help_text='Project IT PM', max_length=50)),
                ('biz_owner', models.CharField(default='', help_text='Project Biz Owner', max_length=50)),
                ('contact_window', models.CharField(default='', help_text='Project Contact Window', max_length=50)),
                ('bu', models.CharField(default='', help_text='BU Names', max_length=20)),
                ('bg', models.CharField(default='', help_text='BG Names', max_length=20)),
                ('bo', models.CharField(default='', help_text='BO Names', max_length=20)),
                ('customer', models.CharField(blank=True, default='', help_text='Project Customer', max_length=50, null=True)),
                ('site', models.CharField(default='', max_length=20)),
                ('plan_start', models.DateField()),
                ('plan_finish', models.DateField()),
                ('recv_ep_code', models.CharField(blank=True, default='', help_text='EP Code', max_length=20, null=True)),
                ('recv_chg_dept', models.CharField(blank=True, default='', help_text='Recv Charge Dept', max_length=10, null=True)),
                ('bud_syst_recv_chg_dept', models.CharField(blank=True, default='', help_text='Budget Syst Recv Charge Dept', max_length=10, null=True)),
                ('project_category', models.CharField(default='', help_text='Projectg Category', max_length=30)),
                ('project_type', models.CharField(default='', help_text='Projectg Type', max_length=30)),
                ('handle_div', models.CharField(default='', help_text='Division Code', max_length=20)),
                ('comments', models.CharField(blank=True, help_text='Project Comments', max_length=300, null=True)),
                ('mis_handle_div_group', models.CharField(default='', help_text='MIS Handle Division Code', max_length=20)),
                ('mis_ib_code', models.CharField(blank=True, default='', help_text='IB Code', max_length=20, null=True)),
                ('pmcs_ib_project_name', models.CharField(default='', help_text='IB Project Name', max_length=100)),
                ('mis_ep_code', models.CharField(blank=True, default='', help_text='MIS EP Code', max_length=20, null=True)),
                ('pmcs_ep_project_name', models.CharField(default='', help_text='EP Project Name', max_length=100)),
                ('cancelled', models.CharField(default='N', help_text='Project Cancelled', max_length=1)),
                ('complete', models.CharField(default='N', help_text='Project Completed', max_length=1)),
                ('split', models.FloatField(default=100.0, help_text='Project Split Percentage')),
                ('creater', models.CharField(blank=True, default='', help_text='PRF Creater', max_length=50, null=True)),
                ('creatdate', models.DateTimeField(blank=True, null=True)),
                ('updater', models.CharField(blank=True, default='', help_text='PRF Updater', max_length=50, null=True)),
                ('updatedate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'imp_prf',
                'unique_together': {('id', 'project_year', 'project_name')},
            },
        ),
    ]
