# Generated by Django 3.2 on 2021-07-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_projtype', '0002_rename_projecttype_projtype_project_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projtype',
            old_name='Project_type',
            new_name='project_type',
        ),
    ]
