# Generated by Django 3.2.6 on 2021-10-15 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_projtype', '0003_rename_project_type_projtype_project_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projtype',
            options={'ordering': ['project_type']},
        ),
    ]
