# Generated by Django 3.2 on 2021-07-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpCal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('countury', models.CharField(default='', help_text='Country Name', max_length=10)),
                ('year', models.CharField(default='', help_text='Year', max_length=5)),
                ('mounth', models.CharField(default='', help_text='Month', max_length=3)),
                ('days', models.IntegerField(default='', help_text='Work Days')),
            ],
            options={
                'db_table': 'imp_Cal',
            },
        ),
    ]
