# Generated by Django 3.2 on 2021-07-15 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='impcal',
            table='imp_cal',
        ),
    ]
