# Generated by Django 3.2 on 2021-07-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_cal', '0004_alter_impcal_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impcal',
            old_name='mounth',
            new_name='month',
        ),
    ]
