# Generated by Django 3.2.6 on 2021-10-15 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_cal', '0005_rename_mounth_impcal_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impcal',
            options={'ordering': ['year', 'month', 'days', 'countury']},
        ),
    ]
