# Generated by Django 3.2.12 on 2022-03-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_cal', '0006_alter_impcal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impcal',
            name='countury',
            field=models.CharField(default='TW', help_text='Country Name', max_length=10),
        ),
        migrations.AlterField(
            model_name='impcal',
            name='month',
            field=models.CharField(default='', help_text='Month', max_length=2),
        ),
        migrations.AlterField(
            model_name='impcal',
            name='year',
            field=models.CharField(default='', help_text='Year', max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='impcal',
            unique_together={('id', 'countury', 'year', 'month')},
        ),
    ]
