# Generated by Django 3.2.12 on 2022-03-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_cal', '0007_auto_20220321_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='impcal',
            name='creatdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='impcal',
            name='creater',
            field=models.CharField(blank=True, help_text='Cal Creater', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='impcal',
            name='updatedate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='impcal',
            name='updater',
            field=models.CharField(blank=True, help_text='Cal Updater', max_length=50, null=True),
        ),
    ]
