# Generated by Django 3.2 on 2021-07-14 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imp_dept', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpTss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employeeid', models.CharField(default='', help_text='Wistron Employee ID', max_length=8)),
                ('employeename', models.CharField(default='', help_text='Wistron Employee Name', max_length=50)),
                ('department', models.CharField(default='', help_text='Wistron Department ID', max_length=10)),
                ('ibcode', models.CharField(default='', help_text='IB Code', max_length=12)),
                ('pmcsibprojectname', models.CharField(default='', help_text='IB Project Name', max_length=100)),
                ('projectleader', models.CharField(default='', help_text='Wistron Project Leader', max_length=50)),
                ('taskcategory', models.CharField(default='', help_text='Task Category on TSS', max_length=50)),
                ('taskitem', models.CharField(default='', help_text='Task Item on TSS', max_length=100)),
                ('date', models.DateField(default='')),
                ('workinghour', models.FloatField(help_text='Working Hour on TSS')),
                ('descriptionmodels', models.CharField(default='', help_text='Description', max_length=100)),
                ('tag', models.CharField(default='', help_text='Tag on TSS', max_length=100)),
                ('profitcentermodels', models.CharField(default='', help_text='Task Item on TSS', max_length=100)),
                ('seq', models.DateTimeField(help_text='Seq DataTime')),
                ('chargedeptid', models.ForeignKey(help_text='Charge Department ID', on_delete=django.db.models.deletion.CASCADE, to='imp_dept.impdept')),
            ],
            options={
                'db_table': 'imp_tss',
                'unique_together': {('id', 'employeeid', 'ibcode', 'taskitem', 'date', 'tag')},
            },
        ),
    ]
