# Generated by Django 3.2 on 2021-07-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_tss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imptss',
            name='profitcenter',
            field=models.CharField(default='', help_text='Profit Center', max_length=100, null=True),
        ),
    ]
