# Generated by Django 3.2 on 2021-07-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_tss', '0002_imptss_profitcenter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imptss',
            old_name='chargedeptid',
            new_name='chargedept',
        ),
    ]
