# Generated by Django 3.2 on 2021-07-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_tss', '0003_rename_chargedeptid_imptss_chargedept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imptss',
            old_name='chargedept',
            new_name='charge_dept',
        ),
        migrations.RenameField(
            model_name='imptss',
            old_name='descriptionmodels',
            new_name='description_models',
        ),
        migrations.RenameField(
            model_name='imptss',
            old_name='employeeid',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='imptss',
            old_name='employeename',
            new_name='employee_name',
        ),
        migrations.RenameField(
            model_name='imptss',
            old_name='ibcode',
            new_name='ib_code',
        ),
        migrations.RenameField(
            model_name='imptss',
            old_name='pmcsibprojectname',
            new_name='pmcs_ib_project_name',
        ),
        migrations.RenameField(
            model_name='imptss',
            old_name='profitcenter',
            new_name='profit_center',
        ),
        migrations.RenameField(
            model_name='imptss',
            old_name='profitcentermodels',
            new_name='profit_center_models',
        ),
        migrations.RenameField(
            model_name='imptss',
            old_name='projectleader',
            new_name='project_leader',
        ),
        migrations.RenameField(
            model_name='imptss',
            old_name='taskcategory',
            new_name='task_category',
        ),
        migrations.RenameField(
            model_name='imptss',
            old_name='taskitem',
            new_name='task_item',
        ),
        migrations.AlterUniqueTogether(
            name='imptss',
            unique_together={('id', 'employee_id', 'ib_code', 'task_item', 'date', 'tag')},
        ),
    ]
