# Generated by Django 3.2 on 2021-07-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_tss', '0004_auto_20210721_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imptss',
            old_name='workinghour',
            new_name='working_hour',
        ),
        migrations.RemoveField(
            model_name='imptss',
            name='description_models',
        ),
        migrations.AddField(
            model_name='imptss',
            name='description',
            field=models.CharField(default='', help_text='Description', max_length=200),
        ),
    ]
