# Generated by Django 3.2 on 2021-07-28 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_tss', '0005_auto_20210722_1020'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imptss',
            unique_together={('id', 'employee_id', 'ib_code', 'task_category', 'task_item', 'date', 'tag')},
        ),
    ]
