# Generated by Django 3.1.7 on 2022-02-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_tss', '0006_alter_imptss_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='imptss',
            name='pmcs_ib_project_year',
            field=models.CharField(default='', help_text='IB Project Year', max_length=4),
        ),
    ]
