# Generated by Django 3.1.7 on 2022-03-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_tss', '0007_imptss_pmcs_ib_project_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imptss',
            name='charge_dept',
            field=models.CharField(default='', help_text='Charge Department', max_length=10),
        ),
    ]
