# Generated by Django 3.1.7 on 2022-03-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_tss', '0009_auto_20220302_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imptss',
            name='description',
            field=models.CharField(default='', help_text='Description', max_length=2000),
        ),
    ]
