# Generated by Django 3.2.6 on 2022-03-05 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_tss', '0007_auto_20220304_1129')
    ]

    operations = [
    ]
