# Generated by Django 3.2.6 on 2022-03-05 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_tss', '0010_auto_20220302_1107'),
        ('imp_tss', '0011_merge_0007_auto_20220304_1129_0010_auto_20220302_1107'),
    ]

    operations = [
    ]
