# Generated by Django 3.2.12 on 2022-04-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPmsUserInJira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_key', models.CharField(help_text='Project Jira Key', max_length=20)),
                ('jira_project_id', models.IntegerField(help_text='Project Jira ID')),
                ('jira_user_id', models.CharField(help_text='User Jira ID', max_length=100)),
                ('display_name', models.CharField(help_text='User Jira Name', max_length=100)),
                ('pms_jira_user_id', models.CharField(help_text='User Jira ID in PMS', max_length=100)),
                ('project_role', models.CharField(help_text='Project Role', max_length=50)),
                ('pms_project_id', models.IntegerField(help_text='Project Jira ID in PMS')),
                ('pms_user_id', models.IntegerField(help_text='PMS User ID')),
                ('division', models.CharField(help_text='Division', max_length=10)),
                ('project_name', models.CharField(help_text='Project Name', max_length=50)),
                ('jira_name', models.CharField(help_text='Jira Project Name', max_length=100)),
            ],
            options={
                'db_table': 'v_pms_user_in_jira',
                'managed': False,
            },
        ),
    ]
