# Generated by Django 3.2 on 2021-07-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PajTxt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issuedept', models.CharField(default='', help_text='Issue Dept', max_length=100)),
                ('issuecode', models.CharField(default='', help_text='Issue Code', max_length=100)),
                ('currency', models.CharField(default='', max_length=100)),
                ('reviewer1', models.CharField(default='', max_length=100)),
                ('reviewer2', models.CharField(default='', max_length=100)),
                ('chargetype', models.CharField(default='', max_length=100)),
                ('shortremark', models.CharField(default='', max_length=100)),
                ('remark', models.CharField(default='', max_length=100)),
                ('sbgchargetype', models.CharField(default='', help_text='SBG Charge Type', max_length=100)),
                ('recvdept', models.CharField(default='', max_length=100)),
                ('recvpcode', models.CharField(default='', max_length=100)),
                ('amount', models.CharField(default='', max_length=100)),
                ('itemtext', models.CharField(default='', max_length=100)),
                ('assignment', models.CharField(default='', max_length=100)),
                ('businesstype', models.CharField(default='', max_length=100)),
                ('customername', models.CharField(default='', max_length=100)),
                ('reason', models.CharField(default='', help_text='Reason', max_length=100)),
            ],
            options={
                'db_table': 'imp_pajtxt',
            },
        ),
    ]
