# Generated by Django 3.2 on 2021-07-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_pajtxt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pajtxt',
            old_name='businesstype',
            new_name='business_type',
        ),
        migrations.RenameField(
            model_name='pajtxt',
            old_name='chargetype',
            new_name='charge_type',
        ),
        migrations.RenameField(
            model_name='pajtxt',
            old_name='customername',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='pajtxt',
            old_name='issuecode',
            new_name='issue_code',
        ),
        migrations.RenameField(
            model_name='pajtxt',
            old_name='issuedept',
            new_name='issue_dept',
        ),
        migrations.RenameField(
            model_name='pajtxt',
            old_name='itemtext',
            new_name='item_text',
        ),
        migrations.RenameField(
            model_name='pajtxt',
            old_name='recvdept',
            new_name='recv_dept',
        ),
        migrations.RenameField(
            model_name='pajtxt',
            old_name='recvpcode',
            new_name='recv_pcode',
        ),
        migrations.RenameField(
            model_name='pajtxt',
            old_name='sbgchargetype',
            new_name='sbg_charge_type',
        ),
        migrations.RenameField(
            model_name='pajtxt',
            old_name='shortremark',
            new_name='short_remark',
        ),
    ]
