# Generated by Django 3.1.7 on 2021-10-25 08:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imp_ib', '0005_alter_impib_options'),
        ('imp_ibln', '0004_auto_20210927_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='impibln',
            name='ib',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imp_ib.impib'),
            preserve_default=False,
        ),
    ]
