# Generated by Django 3.1.7 on 2022-03-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_ibln', '0006_auto_20211026_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='impibln',
            name='creatdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='impibln',
            name='creater',
            field=models.CharField(blank=True, default='', help_text='IBLN Creater', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='impibln',
            name='updatedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='impibln',
            name='updater',
            field=models.CharField(blank=True, default='', help_text='IBLN Updater', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='impibln',
            name='div_group',
            field=models.CharField(default='', help_text='Division Group', max_length=30),
        ),
    ]
