# Generated by Django 3.2.12 on 2022-03-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_ibln', '0007_auto_20220302_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impibln',
            name='creater',
            field=models.CharField(blank=True, default='', help_text='IBLN Creater', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='impibln',
            name='updater',
            field=models.CharField(blank=True, default='', help_text='IBLN Updater', max_length=50, null=True),
        ),
    ]
