# Generated by Django 3.1.7 on 2022-01-20 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pms_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmsProjectVersionControl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version_control', models.CharField(help_text='Version Control', max_length=10)),
                ('type', models.CharField(help_text='type', max_length=10)),
                ('repo_id', models.IntegerField(help_text='Repository ID')),
                ('ut_job_name', models.CharField(help_text='UT Job Name', max_length=20, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pms_prj_version_control_project_id_fkey', to='pms_project.pmsproject')),
            ],
            options={
                'db_table': 'pms_prj_version_control',
                'ordering': ['project_id', 'id'],
            },
        ),
    ]
