# Generated by Django 3.1.7 on 2022-01-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms_project', '0001_initial'),
        ('pms_project_version_control', '0002_auto_20220120_1642'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pmsprojectversioncontrol',
            unique_together={('project_id', 'repo_id')},
        ),
    ]
