# Generated by Django 3.1.7 on 2022-02-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_project_version_control', '0003_auto_20220121_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmsprojectversioncontrol',
            name='repo_url',
            field=models.TextField(help_text='UT Url', null=True),
        ),
    ]
