# Generated by Django 3.1.7 on 2022-03-09 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms_project', '0007_auto_20220224_1025'),
        ('pms_project_version_control', '0004_pmsprojectversioncontrol_repo_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pmsprojectversioncontrol',
            unique_together={('project_id', 'type', 'repo_id')},
        ),
    ]
