# Generated by Django 3.2.12 on 2022-03-29 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms_project', '0007_auto_20220224_1025'),
        ('pms_project_version_control', '0005_auto_20220309_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmsprojectversioncontrol',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pms_prj_version_control_project_id_fkey', to='pms_project.pmsproject'),
        ),
    ]
