# Generated by Django 3.2 on 2021-07-14 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imp_div', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pajln',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ibcode', models.CharField(default='', help_text='IB code', max_length=12)),
                ('pajyear', models.CharField(default='', help_text='PAJ Year', max_length=4)),
                ('janplan', models.FloatField(help_text='Plan HC on Jan')),
                ('febplan', models.FloatField(help_text='Plan HC on feb')),
                ('marplan', models.FloatField(help_text='Plan HC on mar')),
                ('aprplan', models.FloatField(help_text='Plan HC on apr')),
                ('mayplan', models.FloatField(help_text='Plan HC on may')),
                ('junplan', models.FloatField(help_text='Plan HC on June')),
                ('julplan', models.FloatField(help_text='Plan HC on July')),
                ('augplan', models.FloatField(help_text='Plan HC on aug')),
                ('sepplan', models.FloatField(help_text='Plan HC on sep')),
                ('octplan', models.FloatField(help_text='Plan HC on oct')),
                ('novplan', models.FloatField(help_text='Plan HC on nov')),
                ('decplan', models.FloatField(help_text='Plan HC on dec')),
                ('divid', models.ForeignKey(help_text='Division ID', on_delete=django.db.models.deletion.CASCADE, to='imp_div.impdiv')),
            ],
            options={
                'db_table': 'imp_pajln',
                'unique_together': {('id', 'ibcode')},
            },
        ),
    ]
