# Generated by Django 3.2 on 2021-07-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_pajln', '0002_rename_divid_pajln_div'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pajln',
            old_name='aprplan',
            new_name='apr_plan',
        ),
        migrations.RenameField(
            model_name='pajln',
            old_name='augplan',
            new_name='aug_plan',
        ),
        migrations.RenameField(
            model_name='pajln',
            old_name='decplan',
            new_name='dec_plan',
        ),
        migrations.RenameField(
            model_name='pajln',
            old_name='febplan',
            new_name='feb_plan',
        ),
        migrations.RenameField(
            model_name='pajln',
            old_name='ibcode',
            new_name='ib_code',
        ),
        migrations.RenameField(
            model_name='pajln',
            old_name='janplan',
            new_name='jan_plan',
        ),
        migrations.RenameField(
            model_name='pajln',
            old_name='julplan',
            new_name='jul_plan',
        ),
        migrations.RenameField(
            model_name='pajln',
            old_name='junplan',
            new_name='jun_plan',
        ),
        migrations.RenameField(
            model_name='pajln',
            old_name='mayplan',
            new_name='may_plan',
        ),
        migrations.RenameField(
            model_name='pajln',
            old_name='novplan',
            new_name='nov_plan',
        ),
        migrations.RenameField(
            model_name='pajln',
            old_name='octplan',
            new_name='oct_plan',
        ),
        migrations.RenameField(
            model_name='pajln',
            old_name='pajyear',
            new_name='paj_year',
        ),
        migrations.RenameField(
            model_name='pajln',
            old_name='sepplan',
            new_name='sep_plan',
        ),
        migrations.AlterUniqueTogether(
            name='pajln',
            unique_together={('id', 'ib_code')},
        ),
    ]
