# Generated by Django 3.2.6 on 2022-03-21 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_pajln', '0005_auto_20220309_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pajln',
            old_name='marplan',
            new_name='mar_plan',
        ),
    ]
