# Generated by Django 3.2.12 on 2022-03-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_pajln', '0006_rename_marplan_pajln_mar_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pajln',
            name='creatdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pajln',
            name='creater',
            field=models.CharField(blank=True, default='', help_text='PAJLN Creater', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pajln',
            name='updatedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pajln',
            name='updater',
            field=models.CharField(blank=True, default='', help_text='PAJLN Updater', max_length=50, null=True),
        ),
    ]
