# Generated by Django 3.2 on 2021-07-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('projectcategory', models.CharField(default='', help_text='Projectg Category', max_length=30)),
            ],
            options={
                'db_table': 'imp_projcategory',
            },
        ),
    ]
