# Generated by Django 3.2 on 2021-07-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpDiv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('div', models.CharField(default='', help_text='Division ID', max_length=10)),
                ('functions', models.CharField(default='', help_text='Funtion', max_length=30)),
                ('diccode', models.CharField(default='', help_text='Division Code', max_length=20)),
                ('rate', models.IntegerField(default='', help_text='HC Rate')),
            ],
            options={
                'db_table': 'imp_div',
            },
        ),
    ]
