# Generated by Django 3.2 on 2021-07-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_div', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impdiv',
            old_name='diccode',
            new_name='divcode',
        ),
    ]
