# Generated by Django 3.2 on 2021-07-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_div', '0002_rename_diccode_impdiv_divcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impdiv',
            old_name='divcode',
            new_name='div_code',
        ),
    ]
