# Generated by Django 3.2.6 on 2021-10-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_div', '0004_auto_20210927_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impdiv',
            name='functions',
            field=models.CharField(default='', help_text='Funtion', max_length=50),
        ),
    ]
