# Generated by Django 3.2.6 on 2021-10-15 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_div', '0005_alter_impdiv_functions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impdiv',
            options={'ordering': ['div', 'div_group', 'functions', 'rate']},
        ),
    ]
