# Generated by Django 3.2 on 2021-07-14 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imp_bo', '0002_alter_impbo_bo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpBg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bg', models.CharField(default='', help_text='BG Names', max_length=10)),
                ('boid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imp_bo.impbo')),
            ],
            options={
                'db_table': 'imp_bg',
            },
        ),
    ]
