# Generated by Django 3.2 on 2021-07-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_bg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impbg',
            old_name='boid',
            new_name='bo',
        ),
        migrations.AlterField(
            model_name='impbg',
            name='bg',
            field=models.CharField(default='', help_text='BG Names', max_length=20),
        ),
    ]
