# Generated by Django 3.2.12 on 2022-05-03 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pms_project', '0009_pmsproject_jira_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmsSign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sign_id', models.CharField(help_text='Sign ID', max_length=20)),
                ('result', models.CharField(help_text='Result. APPROVED; REJECTED;', max_length=10, null=True)),
                ('remark', models.TextField(help_text='Remark', null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='Created Date')),
                ('signed_date', models.DateTimeField(help_text='Signed Date', null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pms_sign_head_project_id_fkey', to='pms_project.pmsproject')),
            ],
            options={
                'db_table': 'pms_sign_head',
            },
        ),
        migrations.CreateModel(
            name='PmsSignId',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sign_id', models.IntegerField(help_text='Max Sign ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='Created Date')),
            ],
            options={
                'db_table': 'pms_sign_id',
            },
        ),
        migrations.CreateModel(
            name='PmsSignDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seq', models.IntegerField(help_text='Sequence')),
                ('division', models.CharField(help_text='Division', max_length=10)),
                ('sign_user', models.CharField(help_text='Sign User', max_length=50)),
                ('sign_user_email', models.TextField(help_text='Sign User EMail')),
                ('result', models.CharField(help_text='Result. APPROVED; REJECTED;', max_length=10, null=True)),
                ('remark', models.TextField(help_text='Remark', null=True)),
                ('signed_date', models.DateTimeField(help_text='Signed Date', null=True)),
                ('sign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pms_sign_detail_pms_sign_head_id_fkey', to='pms_sign.pmssign')),
            ],
            options={
                'db_table': 'pms_sign_detail',
            },
        ),
    ]
