# Generated by Django 3.2.12 on 2022-05-04 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms_sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pmssign',
            old_name='remark',
            new_name='requester_remark',
        ),
    ]
