# Generated by Django 3.2.12 on 2022-05-06 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms_sign', '0002_rename_remark_pmssign_requester_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmsSignContent',
            fields=[
                ('sign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pms_sign.pmssign')),
                ('project_content', models.JSONField(help_text='Project Content')),
                ('update_user', models.JSONField(help_text='Update User')),
            ],
            options={
                'db_table': 'pms_sign_content',
            },
        ),
    ]
