# Generated by Django 3.2 on 2021-07-14 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imp_div', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpDept',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dept', models.CharField(default='', help_text='Department ID', max_length=10, null=True)),
                ('Deptfrom', models.CharField(default='', help_text='Department From', max_length=10)),
                ('Deptto', models.CharField(default='', help_text='Department To', max_length=10)),
                ('formula', models.IntegerField(default=36, help_text='Formula type:10(0-9) or 36(0-Z)')),
                ('divid', models.ForeignKey(help_text='Division ID', on_delete=django.db.models.deletion.CASCADE, to='imp_div.impdiv')),
            ],
            options={
                'db_table': 'imp_dept',
                'unique_together': {('id', 'dept')},
            },
        ),
    ]
