# Generated by Django 3.2 on 2021-07-20 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_dept', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impdept',
            name='Deptfrom',
        ),
        migrations.RemoveField(
            model_name='impdept',
            name='Deptto',
        ),
        migrations.RemoveField(
            model_name='impdept',
            name='formula',
        ),
    ]
