# Generated by Django 3.2 on 2021-07-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_dept', '0002_auto_20210720_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impdept',
            old_name='divid',
            new_name='div',
        ),
    ]
