# Generated by Django 3.2.6 on 2021-09-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_dept', '0003_rename_divid_impdept_div'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impdept',
            old_name='div',
            new_name='div_group',
        ),
    ]
