# Generated by Django 3.2.6 on 2021-09-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_dept', '0004_rename_div_impdept_div_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impdept',
            old_name='div_group',
            new_name='div',
        ),
    ]
