# Generated by Django 3.2.6 on 2021-10-15 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_dept', '0005_rename_div_group_impdept_div'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impdept',
            options={'ordering': ['dept', 'div']},
        ),
    ]
