# Generated by Django 3.2 on 2021-07-14 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imp_div', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resource', models.CharField(default='', help_text='Team Name', max_length=30)),
                ('divid', models.ForeignKey(help_text='Division ID', on_delete=django.db.models.deletion.CASCADE, to='imp_div.impdiv')),
            ],
            options={
                'db_table': 'imp_resource',
            },
        ),
    ]
