# Generated by Django 3.2 on 2021-07-21 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imp_div', '0003_rename_divcode_impdiv_div_code'),
        ('imp_resource', '0002_rename_divid_resource_div'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='div',
            field=models.ForeignKey(help_text='Division ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='imp_div.impdiv'),
        ),
    ]
