# Generated by Django 3.2.6 on 2021-09-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_resource', '0003_alter_resource_div'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='div',
            new_name='div_group',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='resource',
            new_name='resource_group',
        ),
        migrations.AddField(
            model_name='resource',
            name='division',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='resource',
            name='location',
            field=models.CharField(default='', help_text='location', max_length=30),
        ),
        migrations.AddField(
            model_name='resource',
            name='system',
            field=models.CharField(default='', max_length=30),
        ),
    ]
