# Generated by Django 3.2.6 on 2021-09-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_resource', '0004_auto_20210927_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='remark',
            field=models.CharField(default='', max_length=100),
        ),
    ]
