# Generated by Django 3.2.6 on 2021-09-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_resource', '0005_resource_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='remark',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
