# Generated by Django 3.1.7 on 2021-10-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_resource', '0006_alter_resource_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
