# Generated by Django 3.2.6 on 2021-10-15 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_resource', '0007_auto_20211006_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['resource_group', 'div_group', 'division', 'location', 'system']},
        ),
    ]
