# Generated by Django 3.2 on 2021-07-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_budln', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impbudln',
            old_name='budid',
            new_name='bud',
        ),
        migrations.RenameField(
            model_name='impbudln',
            old_name='resourceid',
            new_name='resource',
        ),
    ]
