# Generated by Django 3.2 on 2021-07-22 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_budln', '0003_auto_20210721_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impbudln',
            old_name='junplan',
            new_name='jun_plan',
        ),
    ]
