# Generated by Django 3.2 on 2021-07-28 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imp_bu', '0002_auto_20210721_1534'),
        ('imp_budln', '0005_impbudln_resource_varchar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impbudln',
            name='bud',
        ),
        migrations.AddField(
            model_name='impbudln',
            name='bu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imp_bu.impbu'),
        ),
    ]
