# Generated by Django 3.2 on 2021-07-28 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imp_bud', '0005_alter_impbud_unique_together'),
        ('imp_budln', '0006_auto_20210728_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impbudln',
            name='bu',
        ),
        migrations.AddField(
            model_name='impbudln',
            name='bud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imp_bud.impbud'),
        ),
    ]
