# Generated by Django 3.2 on 2021-08-26 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_budln', '0007_auto_20210728_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impbudln',
            name='resource_varchar',
        ),
    ]
