# Generated by Django 3.1.7 on 2021-09-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_resource', '0006_alter_resource_remark'),
        ('imp_budln', '0008_remove_impbudln_resource_varchar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='impbudln',
            unique_together={('resource', 'project_year', 'project_name')},
        ),
    ]
