# Generated by Django 3.2.6 on 2021-10-15 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_budln', '0009_auto_20210929_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impbudln',
            options={'ordering': ['project_year', 'project_name', 'resource']},
        ),
    ]
