# Generated by Django 3.1.7 on 2022-01-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_budln', '0010_alter_impbudln_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impbudln',
            name='resource',
            field=models.CharField(default='', help_text='Team Name', max_length=30),
        ),
    ]
