# Generated by Django 3.2 on 2021-07-14 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imp_div', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpIb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('projectyear', models.CharField(default='', help_text='Project Year', max_length=4)),
                ('projectname', models.CharField(default='', help_text='Project Name', max_length=100)),
                ('itpm', models.CharField(default='', help_text='Project IT PM', max_length=50)),
                ('planstart', models.DateField()),
                ('planfinish', models.DateField()),
                ('ibcode', models.CharField(default='', help_text='IB Code', max_length=12)),
                ('pmcsibprojectname', models.CharField(default='', help_text='IB Project Name', max_length=100)),
                ('epcode', models.CharField(default='', help_text='EP Code', max_length=12)),
                ('pmcsepprojectname', models.CharField(default='', help_text='EP Project Name', max_length=100)),
                ('cancelled', models.CharField(default='N', help_text='Project Cancelled', max_length=1)),
                ('complete', models.CharField(default='N', help_text='Project Completed', max_length=1)),
                ('monthlypajdone', models.CharField(default='N', help_text='PAJ done by Monthly', max_length=1)),
                ('handledivid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imp_div.impdiv')),
            ],
            options={
                'db_table': 'imp_ib',
                'unique_together': {('id', 'projectyear', 'projectname', 'ibcode', 'epcode')},
            },
        ),
    ]
