# Generated by Django 3.2.6 on 2021-10-15 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_ib', '0004_rename_handle_div_impib_handle_div_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impib',
            options={'ordering': ['project_year', 'project_name', 'complete', 'cancelled']},
        ),
    ]
