# Generated by Django 3.1.7 on 2022-03-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_ib', '0005_alter_impib_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impib',
            name='handle_div_group',
        ),
        migrations.AddField(
            model_name='impib',
            name='creatdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='impib',
            name='creater',
            field=models.CharField(blank=True, help_text='IB Creater', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='impib',
            name='handle_div',
            field=models.CharField(default='', help_text='Division Code', max_length=20),
        ),
        migrations.AddField(
            model_name='impib',
            name='updatedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='impib',
            name='updater',
            field=models.CharField(blank=True, help_text='IB Updater', max_length=10, null=True),
        ),
    ]
