# Generated by Django 3.1.7 on 2022-03-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_ib', '0006_auto_20220302_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impib',
            name='ib_code',
            field=models.CharField(default='', help_text='IB Code', max_length=20),
        ),
    ]
