# Generated by Django 3.1.7 on 2022-03-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_ib', '0007_auto_20220303_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impib',
            name='ep_code',
            field=models.CharField(default='', help_text='EP Code', max_length=20),
        ),
    ]
