# Generated by Django 3.2.12 on 2022-03-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_ib', '0008_auto_20220303_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impib',
            name='creatdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='impib',
            name='creater',
            field=models.CharField(blank=True, help_text='IB Creater', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='impib',
            name='plan_finish',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='impib',
            name='plan_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='impib',
            name='updatedate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='impib',
            name='updater',
            field=models.CharField(blank=True, help_text='IB Updater', max_length=50, null=True),
        ),
    ]
