# Generated by Django 3.2 on 2021-07-14 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imp_dept', '0001_initial'),
        ('imp_projcategory', '0001_initial'),
        ('imp_div', '0001_initial'),
        ('imp_bu', '0001_initial'),
        ('imp_projtype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpBud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('projectyear', models.CharField(default='', help_text='Project Year', max_length=4)),
                ('projectname', models.CharField(default='', help_text='Project Name', max_length=100)),
                ('itpm', models.CharField(default='', help_text='Project IT PM', max_length=50)),
                ('bizowner', models.CharField(default='', help_text='Project Biz Owner', max_length=50)),
                ('contactwindow', models.CharField(default='', help_text='Project Contact Window', max_length=50)),
                ('customer', models.CharField(default='', help_text='Project Customer', max_length=10, null=True)),
                ('site', models.CharField(default='', max_length=20)),
                ('planstart', models.DateField()),
                ('planfinish', models.DateField()),
                ('recvepcode', models.CharField(default='', help_text='EP Code', max_length=12, null=True)),
                ('comments', models.CharField(default='N', help_text='Project Comments', max_length=200, null=True)),
                ('cancelled', models.CharField(default='N', help_text='Project Cancelled', max_length=1)),
                ('budsystrecvchgdeptid', models.ForeignKey(help_text='Budget Syst Recv Charge Dept', on_delete=django.db.models.deletion.CASCADE, related_name='bud_deptId_2', to='imp_dept.impdept')),
                ('buid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imp_bu.impbu')),
                ('handledivid', models.ForeignKey(help_text='Division ID', on_delete=django.db.models.deletion.CASCADE, to='imp_div.impdiv')),
                ('projectcategoryid', models.ForeignKey(help_text='Project Category ID', on_delete=django.db.models.deletion.CASCADE, to='imp_projcategory.projcategory')),
                ('projecttypeid', models.ForeignKey(help_text='Project Type ID', on_delete=django.db.models.deletion.CASCADE, to='imp_projtype.projtype')),
                ('recvchgdeptid', models.ForeignKey(help_text='Recv Charge Dept', on_delete=django.db.models.deletion.CASCADE, related_name='bud_deptId_1', to='imp_dept.impdept')),
            ],
            options={
                'db_table': 'imp_bud',
                'unique_together': {('id', 'projectyear', 'projectname', 'recvepcode')},
            },
        ),
    ]
