# Generated by Django 3.2 on 2021-07-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_bud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impbud',
            name='recvepcode',
            field=models.CharField(default='', help_text='EP Code', max_length=12),
        ),
    ]
