# Generated by Django 3.2 on 2021-07-28 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_bud', '0004_auto_20210721_1819'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='impbud',
            unique_together={('id', 'project_year', 'project_name')},
        ),
    ]
