# Generated by Django 3.2 on 2021-07-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_bud', '0005_alter_impbud_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impbud',
            name='bud_syst_recv_chg_dept',
            field=models.CharField(default='', help_text='Budget Syst Recv Charge Dept', max_length=10),
        ),
        migrations.AlterField(
            model_name='impbud',
            name='recv_chg_dept',
            field=models.CharField(default='', help_text='Recv Charge Dept', max_length=10),
        ),
    ]
