# Generated by Django 3.2 on 2021-09-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_bud', '0006_auto_20210729_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impbud',
            name='customer',
            field=models.CharField(blank=True, default='', help_text='Project Customer', max_length=10, null=True),
        ),
    ]
