# Generated by Django 3.1.7 on 2021-09-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imp_bud", "0007_alter_impbud_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="impbud",
            name="biz_owner",
            field=models.CharField(
                blank=True, default="", help_text="Project Biz Owner", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="impbud",
            name="bud_syst_recv_chg_dept",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Budget Syst Recv Charge Dept",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="impbud",
            name="comments",
            field=models.CharField(
                blank=True,
                default="N",
                help_text="Project Comments",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="impbud",
            name="contact_window",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Project Contact Window",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="impbud",
            name="it_pm",
            field=models.CharField(
                blank=True, default="", help_text="Project IT PM", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="impbud",
            name="recv_chg_dept",
            field=models.CharField(
                blank=True, default="", help_text="Recv Charge Dept", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="impbud",
            name="recv_ep_code",
            field=models.CharField(
                blank=True, default="", help_text="EP Code", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="impbud",
            name="site",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
