# Generated by Django 3.2 on 2021-09-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_bud', '0007_alter_impbud_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impbud',
            name='comments',
            field=models.CharField(blank=True, default='N', help_text='Project Comments', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='impbud',
            name='recv_ep_code',
            field=models.CharField(blank=True, default='', help_text='EP Code', max_length=12),
        ),
    ]
