# Generated by Django 3.1.7 on 2022-01-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_bud', '0009_alter_impbud_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impbud',
            name='bu',
            field=models.CharField(default='', help_text='BU Names', max_length=20),
        ),
        migrations.AlterField(
            model_name='impbud',
            name='handle_div',
            field=models.CharField(default='', help_text='Division Code', max_length=20),
        ),
        migrations.AlterField(
            model_name='impbud',
            name='project_category',
            field=models.CharField(default='', help_text='Projectg Category', max_length=30),
        ),
        migrations.AlterField(
            model_name='impbud',
            name='project_type',
            field=models.CharField(default='', help_text='Projectg Type', max_length=30),
        ),
    ]
