# Generated by Django 3.1.7 on 2022-03-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_bud', '0010_auto_20220118_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impbud',
            name='comments',
            field=models.CharField(blank=True, help_text='Project Comments', max_length=200, null=True),
        ),
    ]
