# Generated by Django 3.1.7 on 2022-03-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_bud', '0011_auto_20220301_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impbud',
            name='comments',
            field=models.CharField(blank=True, help_text='Project Comments', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='impbud',
            name='recv_ep_code',
            field=models.CharField(blank=True, default='', help_text='EP Code', max_length=20),
        ),
    ]
