# Generated by Django 3.1.7 on 2022-03-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_bud', '0008_auto_20210915_1126'),
        ('imp_bud', '0012_auto_20220301_1930'),
    ]

    operations = [
    ]
