# Generated by Django 3.2.12 on 2022-04-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PmsJiraProjectRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jira_key', models.CharField(help_text='Jira Key', max_length=20)),
                ('jira_project_id', models.IntegerField(help_text='Jira Project ID', null=True)),
                ('project_role', models.CharField(help_text='Project Role', max_length=50)),
                ('jira_user_id', models.CharField(help_text='Jira User ID', max_length=100, null=True)),
            ],
            options={
                'db_table': 'pms_jira_project_role',
                'ordering': ['jira_project_id', 'project_role', 'id'],
            },
        ),
    ]
